### PR TITLE
Fixed tie-vote handling

### LINKED ISSUE #6: Pick random if multiple results are tied
- Probably remove existing random if no votes implementation and replace it with random if multiple max values tied for first

### PR DESCRIPTION
**Pull request by lukemurphy147**
Resolves #6

I'm confident that this code properly handles tie votes now by choosing a random button out of those that tied. However, I'm not so sure about the formatting of `top_result`, since `self.random_button()` and `self.take_action` use different strings for the buttons.

### CODE REVIEW

**Comment by TomCasavant** [comment]
Oh shoot, you're right I didn't notice that. I think I'd prefer if they all showed the emoji in the text so they line up with when a button is actually chosen. If you want to put that in this PR feel free, otherwise I'll just create another issue for it since it's not a huge deal and I'll just go ahead and merge this one in

**Comment by lukemurphy147** [comment]
So it's okay if this part prints the emojis? Right now it doesn't.

image

**Comment by TomCasavant** [comment]
Yes I'd prefer if it shows the emoji like it does for successful votes

**Comment by lukemurphy147** [comment]
OK, the emoji formatting should be consistent now, along with some other things that were bugging me but didn't affect the program logic (gameboy -> Game Boy, mastodon -> Mastodon, etc.) Also, I folded `random_button()` into `take_action()` because I felt like they were too similar.

**Pull request merged**
